apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: pocketid-httproute
spec:
  parentRefs:
    - name: traefik-gateway
      namespace: traefik
  hostnames:
    - "citadel.requiem.garden"
  rules:
    - backendRefs:
        - name: pocketid-service
          port: 80
