# ApplicationSet name
- op: replace
  path: /metadata/name
  value: mimosa-apps-prod

# Git generator pin revision
- op: replace
  path: /spec/generators/0/matrix/generators/0/git/revision
  value: prod

# Git generator path
- op: replace
  path: /spec/generators/0/matrix/generators/0/git/directories/0/path
  value: apps/*/overlays/prod

# Clusters label selector
- op: replace
  path: /spec/generators/0/matrix/generators/1/clusters/selector/matchLabels/env
  value: prod

# Source revision
- op: replace
  path: /spec/template/spec/source/targetRevision
  value: prod
