---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pocketid-secrets
  namespace: pocketid
spec:
  encryptedData:
    ENCRYPTION_KEY: AgAl4m9wYdWzx/bJktq7A7bAkv9fpS+yWQOHvP5Imza8XPZRMLF7w8AhGUMev+ZcBvG2xIQ4hQ09G7uR11hQIirC6xh6ebqsx+47w9VeurO1+hOPkKTizx8v8uXmPkbp77ijVHuTSWh3a8VzTBbCWnoAT5mlZkgvEIC17gNgLEhOnnNdeE72UbJ4T2BcBGlGEq/r2YRXh/7Bwa0xGLl6SG8bkmGVhNpRJAWOUIC8O4S2x+ygEq++UnLhDbQpCux5ATDi9v4tfdB7Vi9rrnKjFDO7BQ5kVxa7MrD3bUMNo/xPQclXa53FmgB1XhPuTnwGh0b6uH4NsRfxXSgH6kZY3neBnVEKNnsRV6AU+Pd2E/wQ0gYcGs/sycqCO6eA8nvNvaFN3yD3pXT4KPhuHqEl2tEp0SV/KxJNUvCcS3Sh/VvMxFGgZ4sjIqNMWc50AJa/ORVqkd+VAiOZFzqZFBU0j6gYYFr8r7eJJGenjZD3eHen/4xD1NLgPlcvaQjvgu08q38JYs+oLlLDAK/dqNqjU1gMvKDaXVrMlE5Nf7ouWFdg65gdU+84SAmuRX5Wm1nkC90DH5FSJnuKSzyS/aGoEYR5fF+rXh+3iFLo4AQRSxg8IDnNeaL3YG3d49XERttz8imV1Ao+8CaSBabPCsBIoz6iY5NG+ziWp8gkz5x9xt0F76EInafgxJ5YE/PX9w9OxnD6OY6lApGfegpbOvWedpZzrK1tVGUkYCJW/x8C4hqu+RKsihSVAsgImyISeA==
    MAXMIND_LICENSE_KEY: AgBHCePXv9pif/5iIgshnLLJS7GurBILXwaFsP4q7GXL7CzD4MNK+V+uHQRAGVcGxt4zdENTn0o8da/zHhvYTcE+qZl6fRHdRCKELO4l9pvC539Nx2f44YLO0Lzt7DhNL05cE5t98n+iRFe6ALs1SBufqFH8Lu56compZT6UHgKIolEvkuP+0snPUuYE2SO+TYooOVOj5IhWchAlkLjknSdX/e52JkV891AjIRLTRhbiOlNsxnnzNnBVjhN5cN5DTICXZNyRfb/VSPSOXP2I95jlDFUKPJPiTcIcUqRI3q/EVq4n5hhr9k3k9yo25egIvSilas6YwD/AwqIarfRNo7XArf4BCRjSWirSgt470PoCpS9Us34jIRoAutSnWYu37W/yD563iqzN+u7+iALyMdBZyU03o7hc3lmP11Me1RtK3pj21hOrdjOPEJt1ahQKmlNdpeNE++QZ7HFmbnSlDd9gLAoEeloYOvAMs3tWtvx1EtXZcYm4FTRHbj0XO4CGZjqgEiDl0FPryweRqK0+r+5ip2lktw7iwtuOYOmsQRYqrh9o+XbV4WmSFv0wkBPzHIxHR0Wb7/oavqbWX/MepRl8SjWKS+Iiy8eJ1fjuAn6Jjh8vuqL65fhUOCn/Y1kDbpvddTh/HlQ2iqNh1VcZrfEUvokR1opG3AYyKCpiBDz+mD0TaXgeANJP1edEBJKRzxieXa2c172S1qIaVHpoePmUlKCeypGjQZ7TcI0qyVIbjXnEv7FF1M2i
  template:
    metadata:
      name: pocketid-secrets
      namespace: pocketid
