apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
  namespace: cert-manager
spec:
  acme:
    email: noa@requiem.garden
    profile: tlsserver
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: rgarden-issuer-account-key
    solvers:
      - dns01:
          cloudflare:
            email: nanekino@outlook.com
            apiTokenSecretRef:
              name: cloudflare-token-secret
              key: api-token
        selector:
          dnsZones:
            - "requiem.garden"
