---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pocketid-secrets
  namespace: pocketid
spec:
  encryptedData:
    ENCRYPTION_KEY: AgB9nQVXx1GBwMQ3ylfSBU7zpMhw+JHci+tTFAlCquzN/uQRnBlS29NBvsNwvUfmHfFQKy3sHwVbQRbERxEyMr2jgjlbA3rZ8TpCXtfmisprprrjMfTTQk821+AADujzflVbH/ulMWAWlM88WVE41slmwu+zZftv6qGH/dnqoYf4QU7ShCIjO6hXFe5Dm7D2/dqi/tb2Y6r+IXj23Hwfv88GNkOuA8aSyG137dswWtbDP68yKPawPC9fwXEPPQyCc8Vv6qpVFxTFCaPx0h5Taci5DR6IKgWcSuC0OtmI1TruiWFIWwRVXKOn/v1vr4Gp1Ew6NBB96yRbihYiKJdGlVX6ZTqj72lYHMvp+iTbAEgrzIvJ2nHdcqvtlTXyHKLtoGs2ZnMcHqNNeKOwyk+Oxs6lXDwVD/zDoNaCEMTyBeBYJKA6G7K2ibheRl5mAL9vOmcPera/EsqVf/hWEeaQDRAmYukw0HkKn3pLSebVt+J++cspq1wB4WOTo4ugrynWFAPn2xEA8LnNiJsdGCZSSLl7mFHXIX8FwoejlX/DfqEyksEP9tDweyP+z/ipdETM127dFtVLhxV1W01pDFmc2VVRPmip2Us0Ul4c7z0Iz6AXNCvJHU3bITULrOv1SJij2v+GWpv9eqB3TVN221Tv7wwi1zQnEBs9tmHILFn2G4VFled0riZKI4tfY6PvBF+TqE+1ILNXfVyVx5J61sLqq2MNkzcZdeofoM6tBHCYojiFnevanF5QCEY6DZURsQ==
    MAXMIND_LICENSE_KEY: AgATJN3CVsGitw7QVOeFz3kPLGGn7YqDpsSRIx89wUE+JAvCxxxaYQ4/d9jOPpCA0DH2WqkKD3w9jzEPPVuhkea/nhynCjO3fJ254SSh15S8rg+yrNzz3z5+r238gWrQwxtPgeQEcHaNmYriwNx81Chv7wjsqTLWb/JjFXEIGti0D9U2zFVrz/tDBxuaUeKw9mK0uguKgWBHk56R87dMA4rv2YS2+wA7BIdvz0xtyY5A8zpnaGDi95V9n0+/WSjS9xGRH/FlG5Ci2g1E5mlkwKeNohIDltBnwmMTuNczc+iWb0b5Hu44X394x60RZeV0a/LM9t0WRHDD/hITeTC7JlXbyy0yiSMHyxnAgM1hgiQwVVPdLyF8wsLwK6nbInCcM9ZkQ3mGUJFXU5soCWfrYeoyCbbBvM+9jSFgOfBVZH2KgsscjDxIuE3MBbpiPYLP5ga8ndMkcJ1l1PeSytEsvLyQvOgqkHZwg1WAqd1GIJsE6QhHDrL0UALV/M62JOR/wIq5wgpdJ2/Ex9OCQkxrPNCzlAFhsul1MJkIdK4XoRMZvX6WD6eMze2HaMZOBaDoFxzRh6Q+gqsrzPiMms4ZlKN1aGgQ46pfPPV4mfWBtQsXgqLM7AtLOQK6Y+O1fVW+2NraIsMHnq9gx4cJKcdU87NTsSBfFyR8emv7modIvPkWwn8zcMbNjtMwLOrbIrGBo7pD6nNa7uZE/X/shC/vVF3B7VDR4D/zMn/cBH/9a23k7PxctnPoFc/c
  template:
    metadata:
      name: pocketid-secrets
      namespace: pocketid
