---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pocketid-secrets
  namespace: pocketid
spec:
  encryptedData:
    ENCRYPTION_KEY: AgBsapMKaWCTtykuacqmyUh1P1CMdhazimZVnTT6AFa2t8WOAYTQS4q3cTUWDFZuhrir8EfpMUAYbwcNgbOZPem+/FdJ+Ruxiel99cp0gc896GI2sK6xQfoZAWnVDXL09SPVoSnL+2+y5Ar3Qz2YIjKg1Nc81LBq3V82VQ9uptwFjj0Z3QU42jddrNWQ2cfcpBiKCyET5W5k5xG8nq0iioyPx/+MMmsTZLBfZXLpGNiYWU04kBx1cEWv6ZKOzYagJqjtA+KS8U0ArK4BJKmJKxjJgxWkOH7GMSnzLcNg3ELBvYC018mpZZ1851/1bHZ6/9vvbEzAiGxYa6VVBxGBlqh1L6s+7WFhqcgFn40vrvA/dqxXEyPiQVrfoPyAIAtT7pFZm57C93+7fuIljWyZ0hD117YwlPKCOwWFui7xI2GoKjcuaBr1ZCYCgs8MY1lj4v2m2fiW72TXPRR+tXc9LD7lG4RQWRtQCzx/OJ7ucfDKuLAH3dfBAW8U6DJkGUgLphYODZmjm/0Z7aCzPCCdDuiloNDWu52SFU833jP5mQ1kFm4X2Upvy/wng37L0+RezLktGdnLjNhuE8Tipebu3zKIiG8h/j0ahAljqboOC6Haet+xNly9Dl5UA6gdH3ASbuW5T+BzOu8mqVCLCo1YhiVMLIOTCnDcLlUA3wAbVQ0ZmUrg9DmxUaPTLR66zjapPr5/6fWf3BoBR4tV2vxwghBbIkEcv+UGMS6LlUXm3xGm2aXz0DYYpOYpzvi2pQ==
    MAXMIND_LICENSE_KEY: AgC5GlHagRwpDdnE9NgM7ZfcG9nF9yDq4jKiPT5GJp6rBGJdpRJ8CVybaJQLP6c3UEsgMk4JXTUziIUqFjtt4tSFK0H9tHvMKtd5fIUVwrFpNWqol62BFnjwS+ADnBy7tDBBf9nTlL4EQ7HFQlf//zOvFsxHBnLnrDeaFaGFSHoZV7NxABeyHE+9x2QBReHMXIBZeyZCkuRPhe+7cEzkSAFhFZDqo1SZ7ayg5xqqaqwNN55W9MRHi/DQZe6xSBXnRyIaJX1mS6Vx/ic8A1MiyayF710TokgNxGJ93xHF6kL/+i+5/E7kfNT7F6u+IbMuP74Z35gG13drEuV9t3A9IA1h4gLRLbKfDrGMiOC7nY/NGDBDiWo4BJSkjUFJPO4wXvAsjf+c1lsDEjBxbzZaBe0cOt0/Q5YRLEFpgx5A6X7SfLDdle4d9Ct+m9+vTVAXgM6pgO6ca5dKzZLjOF9CFfoW3c0NdLyUVsqAjWvq6i3dzGTPJnQ1s/nQgexbmWSA/5HkO0uzww8UOgN0G2GUYsy50bvaWedxX7W4QD440Itsf49UCBYC58WJCFA+ZWblyrhiV7EFt1VnXT2h7imuOwO79dCQSeO0b7hhnzpCUD/SSAKkJe80MDZ5R2yDJJYQMa25/c1hag4IjB5ycoYcjyanAg7gyyNIxdUlbOvSKKjflg37ZhdqM4xtAkvw4NjzYieOqBkC6/i+0rQQua1qlpbLAt1UTR5jhq40K532dr6iHNOPNiAuhI25
  template:
    metadata:
      name: pocketid-secrets
      namespace: pocketid
