---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgAhEa+MEeVVvUFUY+Iid4+W4Fa3/9Zg67V+iMdHvjU9WJKEWRQURb7eKRy8Xn8vflDo/ko0RjbOpJS9AgpPVGfe+cjW0yQMgC7XBZnGchUbJaytaDzt36hnvqJuA0RWDfVwIP2vns7h1ju5mqDRiXHkncRuonSg+nQKwRiuJmzJidVra6HHirZBTe0u9OpQAMnwWGICgNJbMmnY7ZXUgKSb35h3bXKdbP6tPxlbOrWy/GeYiPGV1FOq1qwtyE2YH2jym/Wc3dgyoLT26vyxRH7/bx/hsZjGfFc5FUyZXScidoV6GQGyepFIJOLkvEIpaVgxV4WdAiTjZ0NzZtF4nmM8M7vzDG3VeuMn6RlSZH3q3LtK2+DORp5FBpwuU+Yc8sqEqX6cPbA2ocmpEgh83Zx15U7HvFW5PZkqkPF995A2jLwYUILRFhCLE+EZIfFLINNwUvHdA0X4Adb9tlX5TLR4yuMGROBle3R84nLcmK7HmlS3+uRrIWw5/xvsXwyqfxJbVG6A1+Q2+8/lVEkajuGwM9775Qgk8Bj2zQ76anuYwhXyu19UDj7k+wxyscD+jPyrDKOnJ7sED4UzE1PtGlWxt4+IkjiWL83RcQf2Bsk29JKusD6tQnwJcJ+obTiJ55felGTlzJ1aGmgm4m/ZV7glUZ0dNr/+dIeEeIeXkGt+W9GAmqYRV/iqqEmJBoXRoPjxjD6qjVrdQNMC01ChnEt9AqgiSTfjLMI8H47Q4OfuSkEsEmQuM5Qk
  template:
    metadata:
      name: cloudflare-token-secret
      namespace: cert-manager
