---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgAKJ36r4AYRr/4U6vVxsPF7kzgHhKN80xEXHYNdCp5+pLfCxRkMYmad3ReTBYViVKrMoBOmYNxwaPmW5gZJtQ7UJ9jVB6RhWfN5+qyqLldHPUcYbA30CX+gs7rVftfifPEGzezUjDFhww37ctaEySSDW1lPG7bDSakB/tazwytCvv6UuzdQb+p/5gQxoJa7DjcgLcPMm/8VR2tgKswqd9c5HEZbjjg/rdQXxIMd3g38Ak4yGeR3mw+q+oWIJ197NQs7n0h0Ne9KeRoNLZPPUGt4AK2yu2V7vVnbtyxDVrJd9mmZoP+h7536hwQMSI2ly4HGFC9KfLGO1PjnibL9BkrmRvmZBT5mln9IvUsvJnBwn+Y9BQXpIm/ChlqIKgg/RyjBwf4uFzs6yegMSMTGGV2vS5VJ33PKrYF6C81na0M5KAhj2uwmAtsfsEpCUPmREjX4YYNsS97YG4HBfRlpqy8bZ7kfleuj8shj8JYE9Gwk0xrwD5JkpKHgKYH13FYiSHDXkUZFioXSShp6DHK0gkLsg+jKgyOEFORwGgFY17LOmydX2sCSdvzkcAgrDSMOMWs9nraTzdkBYbORS+gGIAe4fEKRqZFVahvTfbpJfaqJp54Pm6EW2BVYgeqF6Kgh5NgOHmDajHnYgg5hc26CLrrjQ579ANtwvfwiYBb+KhhalmblW0vJifZUxWAUaim2/D81RnGCUbul7Hg6xEmehFDGW8wrnXz3hn10Tc1HFNhGj+VhqB0iSLIf
  template:
    metadata:
      name: cloudflare-token-secret
      namespace: cert-manager
