---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgB+ss/16CKNv6DxwkSjbr9uL3UEWf8v3/nPOrcDnVpoYevESSuskWQKS1W8dFYbkBgv0UoXYWFQcHeBpDoEILPvOLwUbfeR258X1TEbvDqqtlIN2FuNE5tM6LiL0gymMjBDHQWPoGOoVUFuByBd6KYbBrZxH+HCkCEZm1NxLDu80QKbMm+iBJiJufOyS3F4pTQp2rcJxuGiWhNqzagEUHva1+jknrCGDKO3LvxtdY29nmrUVQOfN8/Wj2TEMF5zeLDlgkQQvFpmvuhY8pWPgiSRl+8FY7M99fcBNjDwXjD8nzBCNl7Zbi/NK1Y+2DHYBh3iohDfM4gUph+Gm3Wk1lGcOtEhTG4GYuLIpcG3BcSm8vZMiQVPKjtQwvwrpbeVFhkT/JyKzOFRoR9/JOrcAylISp1fbNdUmXVo4EYTd3QEMVk/z1N5XJySCE+I7U4tLByXgGHKhNU/t9ShKnvUtMFnZa2xGiVJHnmDJMQM9WqkbjhajxaaKEiy3b2N7/6J2rDssp5OM86vdxndqgEmnZjE+cjNOuJehw93qY9XO/513gjlgUGstnWbmWFT9F8zIGFl5aPnoJ2XAblEQGD2enFNpb4nNaUYgxGHuhkNa5hynhz01JdrrQOSn9EyZJqDY4CTQKGqITPjQ2ccq18ebNAZT7KNXh/GQHtiL/of284wahglUZDkJqbkbsaaw6lHZe952ZjTtGJ4WsXKxeUxrjRVNShX00KLQb8xgfGCZWP8g7tCfY2pNkt8
  template:
    metadata:
      name: cloudflare-token-secret
      namespace: cert-manager
